version: '3'
services:
  banking-app-v1:
    build:
      context: .
      dockerfile: Dockerfile.v1
    ports:
      - "8081:8081"
  banking-app-v2:
    build:
      context: .
      dockerfile: Dockerfile.v2
    ports:
      - "8082:8082"
  banking-app-v3:
    build:
      context: .
      dockerfile: Dockerfile.v3
    ports:
      - "8083:8083"
